# Multi-drone farmland layout with drought analytics

areas:
  area_1:
    name: "Farmland 1"
    crop: "Wheat"
    x: -10.0
    y: 10.0
    z: 2.0
    color: "red"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.32
        soil_moisture_index: 0.48
        veg_health_index: 0.60
        heatwave_days: 9
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.41
        soil_moisture_index: 0.44
        veg_health_index: 0.55
        heatwave_days: 11
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.47
        soil_moisture_index: 0.40
        veg_health_index: 0.52
        heatwave_days: 13
        drought_declared: true
      - year: 2024
        rainfall_deficit: 0.54
        soil_moisture_index: 0.36
        veg_health_index: 0.48
        heatwave_days: 15
        drought_declared: true
      - year: 2025
        rainfall_deficit: 0.62
        soil_moisture_index: 0.33
        veg_health_index: 0.41
        heatwave_days: 18
        drought_declared: true

  area_2:
    name: "Farmland 2"
    crop: "Soybean"
    x: 0.0
    y: 10.0
    z: 2.0
    color: "blue"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.12
        soil_moisture_index: 0.62
        veg_health_index: 0.78
        heatwave_days: 5
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.18
        soil_moisture_index: 0.60
        veg_health_index: 0.74
        heatwave_days: 6
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.20
        soil_moisture_index: 0.58
        veg_health_index: 0.72
        heatwave_days: 7
        drought_declared: false
      - year: 2024
        rainfall_deficit: 0.22
        soil_moisture_index: 0.56
        veg_health_index: 0.70
        heatwave_days: 7
        drought_declared: false
      - year: 2025
        rainfall_deficit: 0.24
        soil_moisture_index: 0.54
        veg_health_index: 0.69
        heatwave_days: 8
        drought_declared: false

  area_3:
    name: "Farmland 3"
    crop: "Maize"
    x: 10.0
    y: 10.0
    z: 2.0
    color: "yellow"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.28
        soil_moisture_index: 0.52
        veg_health_index: 0.63
        heatwave_days: 8
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.36
        soil_moisture_index: 0.48
        veg_health_index: 0.58
        heatwave_days: 10
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.44
        soil_moisture_index: 0.45
        veg_health_index: 0.54
        heatwave_days: 12
        drought_declared: true
      - year: 2024
        rainfall_deficit: 0.55
        soil_moisture_index: 0.38
        veg_health_index: 0.49
        heatwave_days: 16
        drought_declared: true
      - year: 2025
        rainfall_deficit: 0.60
        soil_moisture_index: 0.34
        veg_health_index: 0.45
        heatwave_days: 19
        drought_declared: true

  area_4:
    name: "Farmland 4"
    crop: "Barley"
    x: -10.0
    y: 0.0
    z: 2.0
    color: "purple"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.22
        soil_moisture_index: 0.58
        veg_health_index: 0.66
        heatwave_days: 6
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.27
        soil_moisture_index: 0.54
        veg_health_index: 0.61
        heatwave_days: 8
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.35
        soil_moisture_index: 0.50
        veg_health_index: 0.58
        heatwave_days: 9
        drought_declared: false
      - year: 2024
        rainfall_deficit: 0.39
        soil_moisture_index: 0.47
        veg_health_index: 0.55
        heatwave_days: 11
        drought_declared: false
      - year: 2025
        rainfall_deficit: 0.43
        soil_moisture_index: 0.44
        veg_health_index: 0.52
        heatwave_days: 12
        drought_declared: true

  area_5:
    name: "Farmland 5"
    crop: "Vegetables"
    x: 0.0
    y: 0.0
    z: 2.0
    color: "orange"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.08
        soil_moisture_index: 0.68
        veg_health_index: 0.80
        heatwave_days: 3
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.10
        soil_moisture_index: 0.66
        veg_health_index: 0.79
        heatwave_days: 4
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.12
        soil_moisture_index: 0.65
        veg_health_index: 0.78
        heatwave_days: 4
        drought_declared: false
      - year: 2024
        rainfall_deficit: 0.15
        soil_moisture_index: 0.63
        veg_health_index: 0.77
        heatwave_days: 5
        drought_declared: false
      - year: 2025
        rainfall_deficit: 0.17
        soil_moisture_index: 0.62
        veg_health_index: 0.76
        heatwave_days: 5
        drought_declared: false

  area_6:
    name: "Farmland 6"
    crop: "Sunflower"
    x: 10.0
    y: 0.0
    z: 2.0
    color: "cyan"
    size: 10.0
    drought_history:
      - year: 2021
        rainfall_deficit: 0.25
        soil_moisture_index: 0.55
        veg_health_index: 0.64
        heatwave_days: 7
        drought_declared: false
      - year: 2022
        rainfall_deficit: 0.30
        soil_moisture_index: 0.52
        veg_health_index: 0.60
        heatwave_days: 9
        drought_declared: false
      - year: 2023
        rainfall_deficit: 0.37
        soil_moisture_index: 0.49
        veg_health_index: 0.57
        heatwave_days: 10
        drought_declared: false
      - year: 2024
        rainfall_deficit: 0.45
        soil_moisture_index: 0.45
        veg_health_index: 0.53
        heatwave_days: 12
        drought_declared: true
      - year: 2025
        rainfall_deficit: 0.48
        soil_moisture_index: 0.42
        veg_health_index: 0.50
        heatwave_days: 13
        drought_declared: true

# Starting position for all drones
start_position:
  x: 0.0
  y: -10.0
  z: 2.0

# Number of drones
num_drones: 8

# Exploration parameters
exploration:
  patrol_pattern: "grid"
  waypoint_spacing: 2.5
  flight_altitude: 2.0

# Allocation strategy parameters
allocation:
  min_drones_per_area: 1
  max_drones_per_area: 3
  reserve_drones: 2
  measurement_noise: 0.15
  idle_measurement_noise: 0.05
  boundary_soft_margin: 0.4
